### ISSUE TITLE
 AuthType shibboleth configured without corresponding module

### ISSUE THREAD

**Issue by ddilushan** [Renater/Jitsi-SAML2JWT#1]
Getting this error in docker error logs
 `AH01796: AuthType shibboleth configured without corresponding module`
when calling 
https://domain/generateToken?room=r1

**Comment by daimoc** [comment]
Hi @ddilushan,
Thanks for reporting this issue.

Do you have some seen issues on the docker build step ?
And did you run the generate_config_file.sh script before building the docker file ?
 
Regards,
Damien.

**Comment by dilushan** [comment]
it was due to a problem with SERVER_NAME variable. You can close this

**Comment by daimoc** [comment]
That's fine.
