### ISSUE TITLE
Shibboleth package installation

### ISSUE THREAD

**Issue by amitvsipl1** [Renater/Jitsi-SAML2JWT#2]
Hi All,

I want to install Shibboleth package to setup ADFS SSO. we need to install below package

Install Shibboleth SP with fast-cgi support
First, we need to download and install Shibboleth SP packages manually in the following order:

[libmemcached11](https://packages.debian.org/sid/libmemcached11)
[libodbc1](https://packages.debian.org/sid/libodbc1)
[shibboleth-sp2-common](https://packages.debian.org/sid/shibboleth-sp2-common)
[libshibsp6](https://packages.debian.org/sid/libshibsp6)
[libshibsp-plugins](https://packages.debian.org/sid/libshibsp-plugins)
[shibboleth-sp2-utils](https://packages.debian.org/sid/shibboleth-sp2-utils)

These packages are not available. I am appreciating your help and support.

Thanks in advance. 
 

Thanks,
Amit Kumar

**Comment by daimoc** [comment]
Hi @amitvsipl1,
Sorry for the response delay.
I don't know if your question is still relevant, but if you want to install your own Shibboleth SP you can look at the package installed int the docker file.
It can help you to install a Shibboleth SP on last Debian stable.

Regards,
Damien.
